services:
  app:
    env_file:
      - .env
    build: .
    # Uncomment which one is necessary
    # command: bash -c "python manage.py runserver 0.0.0.0:${CONTAINER_PORT}"
    # command: bash -c "gunicorn config.wsgi -w ${UWSGI_WORKERS} -b 0.0.0.0:${CONTAINER_PORT}"
    container_name: juhannus
    volumes:
      - ./app:/app
    ports:
      - "127.0.0.1:${CONTAINER_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
